# Generated by Django 4.1.5 on 2023-02-01 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afloapp', '0002_matiere_formateur_eleve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matiere',
            name='formations',
            field=models.ManyToManyField(related_name='matieres', to='afloapp.formation'),
        ),
    ]
