# Generated by Django 4.1.5 on 2023-02-01 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('afloapp', '0003_alter_matiere_formations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formateur',
            name='formation',
        ),
        migrations.AddField(
            model_name='formation',
            name='responsable',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formation', to='afloapp.formateur'),
        ),
    ]
